### ISSUE TITLE
Options general: Site Language should be moved at the bottom

### ISSUE THREAD

**Issue by afercia** [wpaccessibility/settings-api-enhanced#25]
The Site Language select should be moved after "Week Starts On" for parity with the current WP page. See also what is already done in #16

**Comment by felixarntz** [comment]
I'm not sure how you mean this. Isn't the Site Language setting displayed before Timezone, Date Format etc?

**Comment by afercia** [comment]
Hm this is interesting. on 4.7 (VVV http://local.wordpress.dev/) Site Language is the last setting on the page. On trunk (http://src.wordpress-develop.dev/) is before Timezone.
Maybe we've missed something 🙂 and I'm not sure this change, if intentional, makes much sense. Checking.

**Comment by afercia** [comment]
I18N: Move "Site Language" setting above "Timezone".
https://core.trac.wordpress.org/changeset/39885
> This brings all locale-specific site settings closer together and prevents the language setting from being pushed down by unrelated settings added by plugins.

Hm I guess I'm OK with this, although this change forgot that a spinner is shown close to the Save Changes button only when a new language gets installed. Easy to forget because it was broken 🙂 . See https://core.trac.wordpress.org/ticket/40478
