### ISSUE TITLE
Bold labels

### ISSUE THREAD

**Issue by karmatosed** [wpaccessibility/settings-api-enhanced#33]
I think it would be good to bold all labels. For example this is what it would look like:

![2017-06-04 at 18 19](https://cloud.githubusercontent.com/assets/253067/26763835/71963548-4952-11e7-9095-5d8b9961b554.png)

My thinking it this visually helps distinction. Note, the screenshot includes the font increase I am suggesting too.

**Comment by joyously** [comment]
Are you attempting to gain back the distinction of having two columns gave?
Visually, the two column approach made it very easy to find the label and find the value. Without the columns, it's a muddy mess and hard to find things. So, bold to make them stand out? Like they did before?

**Comment by karmatosed** [comment]
@joyously no I am not, my comment isn't a desire to gain back anything from two columns.

**Comment by joyously** [comment]
Well, I happen to agree that it needs something, probably bold, to set the labels apart from the values now that they are all in the same column.
