### ISSUE TITLE
Permalink settings: custom structure keyboard trap

### ISSUE THREAD

**Issue by afercia** [wpaccessibility/settings-api-enhanced#39]
Noticed just know 😞 the custom structure field has the same keyboard trap that was in the General settings date/time custom format. Fixed in core in https://core.trac.wordpress.org/ticket/40515 and in this plugin in #26 

For core, will open a Trac ticket.

**Comment by afercia** [comment]
See https://core.trac.wordpress.org/ticket/40982

**Comment by felixarntz** [comment]
@afercia Feel free to fix this for the WCEU Milestone if you find time tomorrow and it's an easy thing. I'd like to tag the initial version tomorrow night.

**Comment by afercia** [comment]
Well this still uses `options_permalink_add_js()` from core because there was no reason to change it so I guess better to fix it there. Fixed on trunk in https://core.trac.wordpress.org/changeset/40897
